name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.7.6

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets._GITHUB_TOKEN}}

      - name: Install Dependencies
        run: pnpm i

      # - name: PNPM build
      #   run: pnpm run build

      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # - name: Publish to VSCE & OVSX
      #   run: npm run publish
      #   working-directory: ./packages/vscode
      #   env:
      #     VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
      #     OVSX_TOKEN: ${{secrets.OVSX_TOKEN}}
